// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuiwetzzrohoztbixhth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aXdldHp6cm9ob3p0Yml4aHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjY5NzgsImV4cCI6MjA2NTE0Mjk3OH0.XA19tCBeDW5NUC918Xz8xya2nNtBsBczubtdYv1FWIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);